# Generated by Django 5.0.3 on 2024-04-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=20)),
                ('Main_ing', models.CharField(max_length=50)),
                ('Dish', models.CharField(max_length=100)),
                ('Ing', models.CharField(max_length=1000)),
                ('recipe', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('dish', models.CharField(max_length=100)),
                ('recipe', models.TextField()),
            ],
        ),
    ]
